# Generated by Django 5.2.1 on 2025-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_features_remove_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title'),
        ),
    ]
